###### Importing all the required library

In [5]:
import pandas as pd
import numpy as np

###### Importing the datasets

In [6]:
movies_df=pd.read_csv('tmdb_5000_movies.csv')
credits_df=pd.read_csv('tmdb_5000_credits.csv')

###### Checking the some rows of the above datasets

In [7]:
#movies dataset
movies_df.head(2)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500

In [8]:
#credits datasets
credits_df.head(2)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."

###### Lets check the shape of our datasets

In [9]:
print('Movies Datasets:',movies_df.shape)
print('Credits Datasets:',credits_df.shape)

Movies Datasets: (4803, 20)
Credits Datasets: (4803, 4)

###### Now meerging both the datasets into single one to work more efficiently and create less confusion

In [10]:
#merging datasets based on common column value so that we enter information at the right place for the given title
movies_df=movies_df.merge(credits_df,on='title')
movies_df.shape

(4809, 23)

###### Extracting some important columns that we will be using for the creation feature engineering
genres,
id,
keywords,
title,
overview,
cast,
crew

In [11]:
movies_df=movies_df[['movie_id','title','overview','genres','keywords','cast','crew']]
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

###### Lets check if any of our column contains null values, if 'YES' lets drop them

In [14]:
movies_df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

###### Dropping null values

In [13]:
movies_df.dropna(inplace=True)

###### Lets refine our columns 
- for example:movies_df['genres'][0]
- o/p :
'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'
- ex o/p : ['Action','Adventure','Fantasy'] i.e only 'name'

In [15]:
movies_df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

###### creating helper function that will help us obtain the above results

In [16]:
#The will help us convert strings of dictionary into list of dictionary
import ast

In [21]:
#before lets take backup so that we don't need to start over
moviesbck=movies_df.copy()

In [17]:
def fetch_genre(obj):
    list_genre=[]
    for i in ast.literal_eval(obj):
        list_genre.append(i['name'])
    return list_genre

def fetch_keywords(obj):
    list_kw=[]
    for i in ast.literal_eval(obj):
        list_kw.append(i['name'])
    return list_kw

def fetch_cast(obj):
    list_cast=[]
    counter =0
    for i in ast.literal_eval(obj):
        if counter !=3:
            list_cast.append(i['name'])
            counter+=1
        else:
            break
    return list_cast

def fetch_director(obj):
    list_director=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            list_director.append(i['name'])
            break
    return list_director

In [18]:
movies_df['genres']=movies_df['genres'].apply(fetch_genre)

In [19]:
movies_df['keywords']=movies_df['keywords'].apply(fetch_keywords)

In [20]:
movies_df['cast']=movies_df['cast'].apply(fetch_cast)

In [21]:
movies_df['crew']=movies_df['crew'].apply(fetch_director)

In [22]:
movies_df.sample(5)

,movie_id,title,overview,genres,keywords,cast,crew
3827,35032,The Pirate,"A girl is engaged to the local richman, but me...","[Music, Romance]","[musical, pirate]","[Judy Garland, Gene Kelly, Walter Slezak]",[Vincente Minnelli]
4681,54897,The Grace Card,Everything can change in an instant ... and ta...,[Drama],"[family's daily life, bible, platonic love, ho...","[Michael Joiner, Michael Higgenbottom, Louis G...",[David Evans ]
2955,63020,The Perez Family,In the midst of the Mariel boat lift -- a hurr...,"[Comedy, Drama, Romance]","[immigration, independent film, woman director...","[Marisa Tomei, Alfred Molina, Anjelica Huston]",[Mira Nair]
3897,10162,Waking Ned,"When a lottery winner dies of shock, his fello...","[Comedy, Romance]","[false identity, beguilement, lottery, village...","[Ian Bannen, David Kelly, Fionnula Flanagan]",[Kirk Jones]
1871,10735,What a Girl Wants,"An American girl, Daphne, heads to Europe in s...",[Comedy],"[london england, england, daughter, politician...","[Amanda Bynes, Colin Firth, Kelly Preston]",[Dennie Gordon]

###### Now lets take backup of this dataframe

In [23]:
#backup after refining columns
moviesbck=movies_df.copy()
moviesbck.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

###### Now transfroming the values within our columns to improve recommendation

In [24]:
movies_df['genres']=movies_df['genres'].apply(lambda x :[i.replace(" ","") for i in x])

In [25]:
movies_df['keywords']=movies_df['keywords'].apply(lambda x :[i.replace(" ","") for i in x])

In [26]:
movies_df['cast']=movies_df['cast'].apply(lambda x :[i.replace(" ","") for i in x])

In [27]:
movies_df['crew']=movies_df['crew'].apply(lambda x :[i.replace(" ","") for i in x])

In [28]:
#lets take the backup again
moviesbck=movies_df.copy()
moviesbck.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

###### Now creating a new data frame to filter only the required columns 
- But before that we need to covert them into a string as we cannot concatenate list

In [32]:
(movies_df['genres'].apply(lambda x : " ".join(x)))

0       Action Adventure Fantasy ScienceFiction
1                      Adventure Fantasy Action
2                        Action Adventure Crime
3                   Action Crime Drama Thriller
4               Action Adventure ScienceFiction
                         ...
4804                      Action Crime Thriller
4805                             Comedy Romance
4806               Comedy Drama Romance TVMovie
4807
4808                                Documentary
Name: genres, Length: 4806, dtype: object

In [33]:
movies_df['overview']=movies_df['overview'].apply(lambda x :x.split())
type(movies_df['overview'][0])

list

In [34]:
movies_df['tags']=movies_df['overview']+movies_df['genres']+movies_df['cast']+movies_df['crew']

In [35]:
movies_df['tags']=movies_df['tags'].apply(lambda x :" ".join(x))
movies_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

###### We now have the data in the required format

In [36]:
movies=movies_df[['movie_id','title','tags']]
movies.head()
#taking backup of our latest dataframe
moviesbck=movies.copy()

In [37]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

###### Now we will create a vector of all the keywords from our 'tags' columns
- for that we would require 'from sklearn.feature_extraction.text import CountVectorizer'

In [38]:
from sklearn.feature_extraction.text import CountVectorizer

In [39]:
#instantiating the CountVectorizer class
cv=CountVectorizer(max_features=5000,stop_words='english')

In [40]:
vectors=cv.fit_transform(movies['tags']).toarray()

In [41]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [42]:
# to get all the names 
cv.get_feature_names()

G:\Python\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1944',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970s',
 '1971',
 '1972',
 '1974',
 '1976',
 '1979',
 '1980',
 '1980s',
 '1985',
 '1999',
 '19th',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academic',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'accomplished',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adammckay',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'add',
 'addict',
 'addicted',
 'addiction',
 'adds',
 'adjust',
 'adolescent',
 'adopt',
 'adopted',
 'adopts',
 'adorable',
 'adrienbrody',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affect',
 'affections',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aidanquinn',
 'aided',
 'ailing',
 'aim',
 'air',
 'airborne',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'albert',
 'albertbrooks',
 'alcohol',
 'alcoholic',
 'alecbaldwin',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexapenavega',
 'alexisbledel',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alice',
 'alicebraga',
 'alien',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alter',
 'altering',
 'alternate',
 'alternative',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'amberheard',
 'ambition',
 'ambitious',
 'america',
 'american',
 'americans',
 'amid',
 'amidst',
 'amp',
 'amusement',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andiemacdowell',
 'andrew',
 'andrewniccol',
 'andy',
 'andyfickman',
 'andygarcía',
 'andyserkis',
 'andytennant',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animals',
 'animated',
 'animation',
 'anjelicahuston',
 'ann',
 'anna',
 'annafaris',
 'annakendrick',
 'anne',
 'annehathaway',
 'anneheche',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'announces',
 'annual',
 'anonymous',
 'answer',
 'answers',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthonymackie',
 'anti',
 'antics',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'arab',
 'arch',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'arise',
 'aristocrat',
 'armed',
 'armored',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangement',
 'arranges',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrived',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'article',
 'artificial',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assist',
 'assistance',
 'assistant',
 'assume',
 'assumes',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'athletes',
 'atlantic',
 'atomegoyan',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attend',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'audreytautou',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'auto',
 'autobiographical',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'banished',
 'bank',
 'banker',
 'bar',
 'barbrastreisand',
 'barely',
 'bargained',
 'barney',
 'baron',
 'barry',
 'barrylevinson',
 'barrysonnenfeld',
 'bars',
 'base',
 'baseball',
 'based',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beautiful',
 'beauty',
 'becky',
 'bed',
 'bee',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'belief',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'belong',
 'belongs',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikers',
 'bilbo',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biographical',
 'biography',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarre',
 'black',
 'blackmail',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bonniehunt',
 'book',
 'books',
 'boots',
 'border',
 'bored',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bourne',
 'bout',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'breathing',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brewing',
 'brian',
 'briandepalma',
 'brianlevant',
 'brianrobbins',
 'bride',
 'bridge',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'brooklyn',
 'brooks',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brucecampbell',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutally',
 'bryancranston',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'budget',
 'build',
 'building',
 'builds',
 'built',
 'bully',
 'bumbling',
 'bunch',
 'bunny',
 'buried',
 'burned',
 'burns',
 'burtreynolds',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cal',
 'california',
 'called',
 'calling',
 'calls',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'canine',
 'capable',
 'capital',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'card',
 'care',
 'career',
 'carefree',
 'cares',
 'careymulligan',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'caryelwes',
 'case',
 'cases',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'catch',
 'catches',
 'cateblanchett',
 'catherine',
 'catherinedeneuve',
 'catherinehardwicke',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cave',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'certain',
 'chad',
 'chain',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chazzpalminteri',
 'cheating',
 'chef',
 'chemical',
 'cher',
 'chevychase',
 'chicago',
 'chief',
 'child',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigny',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christopher',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'ciaránhinds',
 'cillianmurphy',
 'cindy',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'claiming',
 'claims',
 'claire',
 'clairedanes',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climb',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closed',
 'closer',
 'closing',
 'closure',
 'club',
 'clubs',
 'clue',
 'clueless',
 'clues',
 'clutches',
 'coach',
 'coast',
 'coastal',
 'cocaine',
 'cocky',
 'code',
 'cody',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehauser',
 'coleridge',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'collapses',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collective',
 'collector',
 'college',
 'collide',
 'collins',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combination',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comfort',
 'comic',
 'comics',
 'coming',
 'command',
 'commander',
 'commanding',
 'commit',
 'commitment',
 'commits',
 'committed',
 'common',
 'communication',
 'communist',
 'community',
 'companion',
 'companions',
 'company',
 'compete',
 'competing',
 'competition',
 'competitive',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'compton',
 'compulsive',
 'computer',
 'conan',
 'concerning',
 'concert',
 'conclusion',
 'condition',
 'conditions',
 'confidence',
 'confident',
 'conflict',
 'conflicts',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'connect',
 'connected',
 'connecticut',
 'connection',
 'connections',
 'connects',
 'connell',
 'connie',
 'connienielsen',
 'connor',
 'conquer',
 'conrad',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'considers',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'containing',
 'contains',
 'contemporary',
 'contend',
 'contest',
 'continent',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convicts',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corleone',
 'corner',
 'corners',
 'corporate',
 'corporation',
 ...]

###### We can see that there are few words repeated like 'actions','action' similarly our dataset can have multiple amount of repeatition.
- This can be resolve using 'from nltk.stem.porter import PorterStemmer'

In [36]:
import nltk
from nltk.stem.porter import PorterStemmer

In [37]:
#Instantiating PortStemmer class
ps=PorterStemmer()
#we will apply stem on our 'tags' column
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [38]:
movies['tags']=movies['tags'].apply(stem)

C:\WINDOWS\TEMP/ipykernel_4800/4136005365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(stem)

In [39]:
vectors=cv.fit_transform(movies['tags']).toarray()

In [40]:
#we have now eliminated the repeated words
cv.get_feature_names()

G:\Python\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '12th',
 '13',
 '14',
 '15',
 '150',
 '16',
 '17',
 '17th',
 '18',
 '1890',
 '18th',
 '19',
 '1920',
 '1930',
 '1930s',
 '1937',
 '1940',
 '1941',
 '1944',
 '1945',
 '1950',
 '1950s',
 '1955',
 '1959',
 '1960',
 '1960s',
 '1962',
 '1964',
 '1965',
 '1967',
 '1970',
 '1970s',
 '1971',
 '1972',
 '1973',
 '1974',
 '1976',
 '1977',
 '1979',
 '1980',
 '1980s',
 '1984',
 '1985',
 '1990',
 '1994',
 '1997',
 '1999',
 '19th',
 '20',
 '200',
 '2000',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'aarontaylor',
 'abandon',
 'abbi',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abroad',
 'absolut',
 'abus',
 'academ',
 'academi',
 'academy',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'acquir',
 'act',
 'action',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adammckay',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adrift',
 'adult',
 'adulthood',
 'adults',
 'advanc',
 'advantag',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'affluent',
 'afghanistan',
 'afraid',
 'africa',
 'african',
 'aftermath',
 'ag',
 'age',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airborn',
 'aircraft',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alanarkin',
 'alaska',
 'alaskan',
 'albert',
 'albertbrook',
 'albertfinney',
 'alcohol',
 'alecbaldwin',
 'alejandrogonzáleziñárritu',
 'alex',
 'alexanderpayn',
 'alexanderskarsgård',
 'alexapenavega',
 'alexia',
 'alexisbledel',
 'alexkendrick',
 'alexpettyf',
 'alexproya',
 'alfi',
 'alfredhitchcock',
 'alfredmolina',
 'algeria',
 'ali',
 'alic',
 'alice',
 'alicebraga',
 'alien',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'alleg',
 'allen',
 'alli',
 'allianc',
 'allies',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandabyn',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'amberheard',
 'ambit',
 'ambiti',
 'ambush',
 'america',
 'american',
 'ami',
 'amid',
 'amidst',
 'amp',
 'amus',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'ancient',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'andrewadamson',
 'andrewgarfield',
 'andrewniccol',
 'andrzejbartkowiak',
 'andy',
 'andyfickman',
 'andygarcía',
 'andyserki',
 'andytenn',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annefletch',
 'annehathaway',
 'annehech',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'answers',
 'ant',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anti',
 'antic',
 'antiqu',
 'antoinefuqua',
 'anton',
 'antonio',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appli',
 'appoint',
 'appreci',
 'apprehend',
 'apprentic',
 'approach',
 'approaches',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'array',
 'arrest',
 'arriv',
 'arrives',
 'arrog',
 'art',
 'arthur',
 'articl',
 'artifici',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assignment',
 'assist',
 'assistant',
 'associ',
 'assum',
 'astronaut',
 'asylum',
 'athlet',
 'atlant',
 'atom',
 'atomegoyan',
 'attack',
 'attacks',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'audreytaut',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'auto',
 'autobiograph',
 'avail',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'awar',
 'award',
 'away',
 'awesom',
 'awkward',
 'awri',
 'awry',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backyard',
 'bad',
 'bag',
 'bail',
 'baker',
 'balanc',
 'ball',
 'ballet',
 'ban',
 'band',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bar',
 'barbara',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrier',
 'barry',
 'barrylevinson',
 'barrypepp',
 'barrysonnenfeld',
 'bars',
 'bas',
 'base',
 'basebal',
 'basement',
 'basketbal',
 'basketball',
 'batman',
 'battalion',
 'battl',
 'battle',
 'bay',
 'beach',
 'beam',
 'bear',
 'beast',
 'beat',
 'beaten',
 'beau',
 'beauti',
 'beautiful',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'bed',
 'bedroom',
 'bee',
 'befor',
 'befriend',
 'beg',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'beliefs',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'berniemac',
 'best',
 'bet',
 'beth',
 'betray',
 'betrayal',
 'bettemidl',
 'better',
 'betti',
 'bettythoma',
 'beverli',
 'biblic',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bilbo',
 'billcondon',
 'billhad',
 'billi',
 'billion',
 'billionair',
 'billmoseley',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billyconnolli',
 'billycrudup',
 'billycryst',
 'bind',
 'biograph',
 'biographi',
 'biolog',
 'biologist',
 'biopic',
 'bird',
 'birth',
 'birthday',
 'bishop',
 'bit',
 'bitter',
 'bizarr',
 'black',
 'blackmail',
 'blade',
 'blame',
 'blaze',
 'blend',
 'bless',
 'blind',
 'bliss',
 'block',
 'blood',
 'bloodi',
 'bloodthirsti',
 'bloom',
 'blossom',
 'blow',
 'blu',
 'blue',
 'board',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bomb',
 'bond',
 'bone',
 'bonniehunt',
 'book',
 'border',
 'bore',
 'boring',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bout',
 'box',
 'boxer',
 'boy',
 'boyd',
 'boyfriend',
 'boys',
 'brad',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'brazil',
 'break',
 'breakdown',
 'breakup',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'brianlev',
 'brianrobbin',
 'bride',
 'bridg',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'brook',
 'brooklyn',
 'brother',
 'brothers',
 'brought',
 'brown',
 'bruce',
 'brucecampbel',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryancranston',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'buri',
 'burn',
 'burtreynold',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butch',
 'butcher',
 'butler',
 'butt',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cain',
 'cal',
 'caleb',
 'california',
 'calm',
 'calvin',
 'came',
 'camera',
 'cameraman',
 'cameron',
 'cameroncrow',
 'camerondiaz',
 'camgigandet',
 'camp',
 'campaign',
 'campbel',
 'campbell',
 'campbellscott',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'card',
 'care',
 'career',
 'carefre',
 'careymulligan',
 'cargo',
 'caribbean',
 'carl',
 'carlagugino',
 'carlo',
 'carmen',
 'carol',
 'carolina',
 'carri',
 'carrie',
 'carriefish',
 'cartel',
 'carter',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'castle',
 'cat',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherin',
 'catherinedeneuv',
 'catherinehardwick',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'cattl',
 'caught',
 'caus',
 'cause',
 'cave',
 'cedrictheentertain',
 'celebr',
 'celebration',
 'cell',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channel',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charless',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlott',
 'charm',
 'chart',
 'chase',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childhood',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'choic',
 'choice',
 'chon',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christoph',
 'christopherguest',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'chuckrussel',
 'church',
 'cia',
 'ciaránhind',
 'cillianmurphi',
 'cindi',
 'cinema',
 'circl',
 'circle',
 'circu',
 'circuit',
 'circumst',
 'circumstances',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilization',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'coastal',
 'cocain',
 'cocki',
 'code',
 'codi',
 'cohen',
 'col',
 'cold',
 'cole',
 'colehaus',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'collapse',
 'colleagu',
 'colleague',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collide',
 'collis',
 'colon',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'command',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compound',
 'compromis',
 'compton',
 'compuls',
 'comput',
 'computer',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'connect',
 'connecticut',
 'connel',
 'conni',
 'connienielsen',
 'connor',
 'conquer',
 'conrad',
 'conscience',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contempl',
 'contemporari',
 'contend',
 'content',
 'contest',
 'contin',
 ...]

In [43]:
#lets take backup of the transform dataset
moviesbcktr=movies.copy()
moviesbcktr.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

###### Now we have converted our 'tags' columns to a vector for comparing each vector with eachother
- To achieve this we will be using library that will do the work for us 'from sklearn.metrics.pairwise import cosine_similarity'

In [44]:
from sklearn.metrics.pairwise import cosine_similarity

In [45]:
similarity=cosine_similarity(vectors)

In [46]:
similarity[1]

array([0.15389675, 1.        , 0.08830216, ..., 0.03673592, 0.        ,
       0.        ])

In [48]:
similarity.shape

(4806, 4806)

In [49]:
#main recommendation logic
def recommend(movie):
    movie_idx=movies[movies['title']==movie].index[0]
    distances=similarity[movie_idx]
    movies_list=sorted(list(enumerate(distances)),reverse=True,key=lambda x : x[1])[1:6]
    for i in movies_list:
        print(movies.iloc[i[0]].title)

In [50]:
recommend('Gandhi')

Gandhi, My Father
A Passage to India
Ramanujan
Chariots of Fire
Mr. Turner

In [51]:
import pickle

In [59]:
pickle.dump(movies.to_dict(),open('movies_dict.pkl','wb'))

In [60]:
pickle.dump(similarity,open('similarity.pkl','wb'))

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [88]:
movies[movies['title']=='Avatar'].movie_id[0]

19995