In [1]:
import pandas as pd
import numpy as np

In [190]:
import nltk
from nltk.stem.porter import PorterStemmer

In [216]:
from sklearn.metrics.pairwise import cosine_similarity

In [178]:
from sklearn.feature_extraction.text import CountVectorizer

In [95]:
movies_df=pd.read_csv('tmdb_5000_movies.csv')
credits_df=pd.read_csv('tmdb_5000_credits.csv')

In [96]:
movies_df.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [97]:
credits_df.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [98]:
movies_df=movies_df.merge(credits_df,on='title')
movies_df.shape

(4809, 23)

In [99]:
movies_df.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [100]:
#important columns
#genres
#id
#keywords
#title
#overview
#cast
#crew

In [101]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [102]:
movies_df=movies_df[['movie_id','title','overview','genres','keywords','cast','crew']]

In [103]:
movies_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [104]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [105]:
movies_df.dropna(inplace=True)

In [106]:
movies_df.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [107]:
movies_df.duplicated().sum()

0

In [113]:
movies_df.iloc[0].genres

str

In [114]:
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [115]:
def fetch_tags(obj):
    list_tag=[]
    for i in ast.literal_eval(obj):
        list_tag.append(i['name'])
    return list_tag
convert('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [116]:
movies_df['genres']=movies_df['genres'].apply(fetch_tags)

In [117]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [50]:
movies_df['keywords']=movies_df['keywords'].apply(convert)

In [51]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [251]:
def fetch_cast(obj):
    list_cast=[]
    counter =0
    for i in ast.literal_eval(obj):
        if counter !=3:
            list_cast.append(i['name'])
            counter+=1
        else:
            break
    return list_cast

In [254]:
moviesbk['cast'][0]

['Sam Worthington',
 'Zoe Saldana',
 'Sigourney Weaver',
 'Stephen Lang',
 'Michelle Rodriguez',
 'Giovanni Ribisi',
 'Joel David Moore',
 'CCH Pounder',
 'Wes Studi',
 'Laz Alonso',
 'Dileep Rao',
 'Matt Gerald',
 'Sean Anthony Moran',
 'Jason Whyte',
 'Scott Lawrence',
 'Kelly Kilgour',
 'James Patrick Pitt',
 'Sean Patrick Murphy',
 'Peter Dillon',
 'Kevin Dorman',
 'Kelson Henderson',
 'David Van Horn',
 'Jacob Tomuri',
 'Michael Blain-Rozgay',
 'Jon Curry',
 'Luke Hawker',
 'Woody Schultz',
 'Peter Mensah',
 'Sonia Yee',
 'Jahnel Curfman',
 'Ilram Choi',
 'Kyla Warren',
 'Lisa Roumain',
 'Debra Wilson',
 'Chris Mala',
 'Taylor Kibby',
 'Jodie Landau',
 'Julie Lamm',
 'Cullen B. Madden',
 'Joseph Brady Madden',
 'Frankie Torres',
 'Austin Wilson',
 'Sara Wilson',
 'Tamica Washington-Miller',
 'Lucy Briant',
 'Nathan Meister',
 'Gerry Blair',
 'Matthew Chamberlain',
 'Paul Yates',
 'Wray Wilson',
 'James Gaylyn',
 'Melvin Leno Clark III',
 'Carvon Futrell',
 'Brandon Jelkes',
 'Micah Moch',
 'Hanniyah Muhammad',
 'Christopher Nolen',
 'Christa Oliver',
 'April Marie Thomas',
 'Bravita A. Threatt',
 'Colin Bleasdale',
 'Mike Bodnar',
 'Matt Clayton',
 'Nicole Dionne',
 'Jamie Harrison',
 'Allan Henry',
 'Anthony Ingruber',
 'Ashley Jeffery',
 'Dean Knowsley',
 'Joseph Mika-Hunt',
 'Terry Notary',
 'Kai Pantano',
 'Logan Pithyou',
 'Stuart Pollock',
 'Raja',
 'Gareth Ruck',
 'Rhian Sheehan',
 'T. J. Storm',
 'Jodie Taylor',
 'Alicia Vela-Bailey',
 'Richard Whiteside',
 'Nikie Zambo',
 'Julene Renee']

In [63]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weave...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman, A...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [124]:
type(movies_df['crew'][0])

str

In [125]:
def fetch_director(obj):
    list_director=[]
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            list_director.append(i['name'])
            break
    return list_director

In [89]:
movies_df['crew'][0]

[]

In [126]:
moviesbk=movies_df.copy()

In [128]:
movies_df['crew']=movies_df['crew'].apply(fetch_director)

In [139]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [130]:
movies_df['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [131]:
movies_df['overview']=movies_df['overview'].apply(lambda x :x.split())

In [132]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[Sam Worthington, Zoe Saldana, Sigourney Weave...",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[Johnny Depp, Orlando Bloom, Keira Knightley, ...",[Gore Verbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux, R...",[Sam Mendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[Christian Bale, Michael Caine, Gary Oldman, A...",[Christopher Nolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[Taylor Kitsch, Lynn Collins, Samantha Morton,...",[Andrew Stanton]

In [136]:
movies_df['genres']=movies_df['genres'].apply(lambda x :[i.replace(" ","") for i in x])

In [137]:
movies_df['keywords']=movies_df['keywords'].apply(lambda x :[i.replace(" ","") for i in x])
movies_df['cast']=movies_df['cast'].apply(lambda x :[i.replace(" ","") for i in x])
movies_df['crew']=movies_df['crew'].apply(lambda x :[i.replace(" ","") for i in x])

In [138]:
movies_df.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton]

In [147]:
movies_df.drop('keywords',1,inplace=True)

C:\WINDOWS\TEMP/ipykernel_11096/161951869.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  movies_df.drop('keywords',1,inplace=True)

KeyError: "['keywords'] not found in axis"

In [253]:
movies_df.head()

,movie_id,title,overview,genres,cast,crew,keywords,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili..."

In [154]:
val=movies_df['keywords'][0]

In [155]:
def fetch_keywords(obj):
    list_keywords=[]
    for i in ast.literal_eval(obj):
        list_keywords.append(i['name'])
    return list_keywords
print(fetch_keywords(val))

['culture clash', 'future', 'space war', 'space colony', 'society', 'space travel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alien planet', 'cgi', 'marine', 'soldier', 'battle', 'love affair', 'anti war', 'power relations', 'mind and soul', '3d']

In [159]:
movies_df['keywords']=movies_df['keywords'].apply(fetch_keywords)

ValueError: malformed node or string: ['culture clash', 'future', 'space war', 'space colony', 'society', 'space travel', 'futuristic', 'romance', 'space', 'alien', 'tribe', 'alien planet', 'cgi', 'marine', 'soldier', 'battle', 'love affair', 'anti war', 'power relations', 'mind and soul', '3d']

In [160]:
movies_df.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[culture clash, future, space war, space colon..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drug abuse, exotic island, east india ..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[spy, based on novel, secret agent, sequel, mi..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[dc comics, crime fighter, terrorist, secret i..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[based on novel, mars, medallion, space travel..."

In [164]:
movies_df['keywords']=movies_df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [165]:
movies_df.head()

,movie_id,title,overview,genres,cast,crew,keywords
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p..."

In [258]:
movies_df['tags']=movies_df['overview']+movies_df['genres']+movies_df['cast']+movies_df['crew']

In [259]:
movies_df.head()

,movie_id,title,overview,genres,cast,crew,keywords,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili..."

In [255]:
movies_df.head()

,movie_id,title,overview,genres,cast,crew,keywords,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[SamWorthington, ZoeSaldana, SigourneyWeaver, ...",[JamesCameron],"[cultureclash, future, spacewar, spacecolony, ...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...",[GoreVerbinski],"[ocean, drugabuse, exoticisland, eastindiatrad...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[DanielCraig, ChristophWaltz, LÃ©aSeydoux, Ralp...",[SamMendes],"[spy, basedonnovel, secretagent, sequel, mi6, ...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[ChristianBale, MichaelCaine, GaryOldman, Anne...",[ChristopherNolan],"[dccomics, crimefighter, terrorist, secretiden...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[TaylorKitsch, LynnCollins, SamanthaMorton, Wi...",[AndrewStanton],"[basedonnovel, mars, medallion, spacetravel, p...","[John, Carter, is, a, war-weary,, former, mili..."

In [243]:
movies=movies_df[['movie_id','title','tags']]

In [246]:
movies['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction SamWorthington ZoeSaldana SigourneyWeaver StephenLang MichelleRodriguez GiovanniRibisi JoelDavidMoore CCHPounder WesStudi LazAlonso DileepRao MattGerald SeanAnthonyMoran JasonWhyte ScottLawrence KellyKilgour JamesPatrickPitt SeanPatrickMurphy PeterDillon KevinDorman KelsonHenderson DavidVanHorn JacobTomuri MichaelBlain-Rozgay JonCurry LukeHawker WoodySchultz PeterMensah SoniaYee JahnelCurfman IlramChoi KylaWarren LisaRoumain DebraWilson ChrisMala TaylorKibby JodieLandau JulieLamm CullenB.Madden JosephBradyMadden FrankieTorres AustinWilson SaraWilson TamicaWashington-Miller LucyBriant NathanMeister GerryBlair MatthewChamberlain PaulYates WrayWilson JamesGaylyn MelvinLenoClarkIII CarvonFutrell BrandonJelkes MicahMoch HanniyahMuhammad ChristopherNolen ChristaOliver AprilMarieThomas BravitaA.Threatt ColinBleasdale MikeBodnar MattClayton NicoleDionne JamieHarrison AllanHenry AnthonyIngruber AshleyJeffery DeanKnowsley JosephMika-Hunt TerryNotary KaiPantano LoganPithyou StuartPollock Raja GarethRuck RhianSheehan T.J.Storm JodieTaylor AliciaVela-Bailey RichardWhiteside NikieZambo JuleneRenee JamesCameron'

In [245]:
movies['tags']=movies['tags'].apply(lambda x :" ".join(x))

C:\WINDOWS\TEMP/ipykernel_11096/1665823243.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(lambda x :" ".join(x))

In [176]:
movies['tags']=movies['tags'].apply(lambda x : x.lower())

C:\WINDOWS\TEMP/ipykernel_11096/957850832.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(lambda x : x.lower())

In [177]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [210]:
cv=CountVectorizer(max_features=500,stop_words='english')
vectors=cv.fit_transform(movies['tags']).toarray()

In [217]:
vectors

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [212]:
vectors.shape

(4806, 500)

In [213]:
cv.get_feature_names()

['accident',
 'act',
 'action',
 'adventur',
 'affair',
 'age',
 'agent',
 'agre',
 'alien',
 'alway',
 'america',
 'american',
 'ancient',
 'angel',
 'ani',
 'anim',
 'anoth',
 'anyth',
 'apart',
 'arm',
 'armi',
 'arriv',
 'art',
 'artist',
 'ask',
 'assassin',
 'assign',
 'attack',
 'attempt',
 'away',
 'bad',
 'band',
 'base',
 'battl',
 'beauti',
 'becom',
 'befor',
 'begin',
 'believ',
 'best',
 'big',
 'black',
 'blood',
 'bodi',
 'bond',
 'book',
 'boss',
 'boy',
 'boyfriend',
 'break',
 'brien',
 'bring',
 'british',
 'brother',
 'brown',
 'brucewilli',
 'build',
 'busi',
 'california',
 'captain',
 'captur',
 'car',
 'career',
 'case',
 'caught',
 'caus',
 'center',
 'centuri',
 'challeng',
 'chanc',
 'chang',
 'charact',
 'child',
 'childhood',
 'children',
 'cia',
 'citi',
 'city',
 'class',
 'close',
 'club',
 'coach',
 'colleg',
 'come',
 'comedi',
 'commun',
 'compani',
 'confront',
 'connor',
 'continu',
 'control',
 'convinc',
 'cop',
 'corrupt',
 'countri',
 'coupl',
 'crash',
 'creat',
 'creatur',
 'crew',
 'crime',
 'crimin',
 'cross',
 'danger',
 'dark',
 'daughter',
 'david',
 'day',
 'dead',
 'deadli',
 'deal',
 'death',
 'decid',
 'desert',
 'desper',
 'despit',
 'destroy',
 'detect',
 'determin',
 'develop',
 'die',
 'differ',
 'director',
 'disappear',
 'discov',
 'doctor',
 'documentari',
 'doe',
 'doesn',
 'dog',
 'don',
 'dr',
 'drama',
 'dream',
 'drug',
 'dure',
 'earth',
 'embark',
 'encount',
 'end',
 'enter',
 'entir',
 'epic',
 'escap',
 'event',
 'everi',
 'everyon',
 'everyth',
 'evil',
 'ex',
 'execut',
 'exist',
 'experi',
 'eye',
 'face',
 'fail',
 'fall',
 'famili',
 'family',
 'fantasi',
 'far',
 'fate',
 'father',
 'fbi',
 'fear',
 'feel',
 'fight',
 'film',
 'final',
 'follow',
 'forc',
 'form',
 'frank',
 'free',
 'french',
 'friend',
 'friends',
 'friendship',
 'futur',
 'game',
 'gang',
 'gener',
 'girl',
 'girlfriend',
 'god',
 'goe',
 'good',
 'govern',
 'great',
 'group',
 'grow',
 'guy',
 'ha',
 'hand',
 'happen',
 'happi',
 'hard',
 'head',
 'heart',
 'help',
 'hero',
 'hi',
 'high',
 'hire',
 'histori',
 'hit',
 'hold',
 'home',
 'hope',
 'horror',
 'hous',
 'human',
 'hunt',
 'hunter',
 'husband',
 'ii',
 'includ',
 'insid',
 'inspir',
 'intern',
 'investig',
 'involv',
 'island',
 'jack',
 'jackson',
 'jame',
 'jean',
 'job',
 'john',
 'johnc',
 'johnson',
 'join',
 'jon',
 'journey',
 'jr',
 'just',
 'kid',
 'kidnap',
 'kill',
 'killer',
 'king',
 'know',
 'known',
 'la',
 'land',
 'late',
 'later',
 'law',
 'lawyer',
 'lead',
 'leader',
 'learn',
 'leav',
 'led',
 'left',
 'legendari',
 'lie',
 'life',
 'like',
 'littl',
 'live',
 'lives',
 'lo',
 'local',
 'london',
 'long',
 'look',
 'lose',
 'lost',
 'love',
 'lover',
 'magic',
 'make',
 'man',
 'manag',
 'mani',
 'mark',
 'marri',
 'martin',
 'master',
 'mean',
 'meet',
 'member',
 'men',
 'michael',
 'militari',
 'million',
 'mind',
 'miss',
 'mission',
 'modern',
 'money',
 'mother',
 'movi',
 'mr',
 'murder',
 'music',
 'mysteri',
 'nation',
 'need',
 'neil',
 'new',
 'nick',
 'night',
 'noth',
 'novel',
 'obsess',
 'offer',
 'offic',
 'old',
 'onc',
 'onli',
 'open',
 'oper',
 'order',
 'owner',
 'pair',
 'parent',
 'parents',
 'park',
 'parti',
 'partner',
 'past',
 'path',
 'peopl',
 'perfect',
 'person',
 'peter',
 'place',
 'plan',
 'planet',
 'play',
 'plot',
 'polic',
 'polit',
 'popular',
 'power',
 'presid',
 'prison',
 'problem',
 'protect',
 'prove',
 'pursu',
 'queen',
 'quest',
 'question',
 'quickli',
 'race',
 'rais',
 'real',
 'realiz',
 'realli',
 'receiv',
 'recent',
 'reilli',
 'relationship',
 'remain',
 'report',
 'rescu',
 'return',
 'reunit',
 'reveal',
 'reveng',
 'right',
 'rise',
 'rival',
 'road',
 'robert',
 'robertdeniro',
 'rock',
 'role',
 'romanc',
 'romant',
 'rule',
 'run',
 'ruthless',
 'sam',
 'samuell',
 'save',
 'scheme',
 'school',
 'sciencefict',
 'scientist',
 'search',
 'second',
 'secret',
 'secur',
 'seek',
 'seemingli',
 'self',
 'send',
 'sent',
 'seri',
 'set',
 'sever',
 'sex',
 'sexual',
 'share',
 'ship',
 'sinc',
 'singer',
 'singl',
 'sister',
 'small',
 'smith',
 'soldier',
 'someth',
 'son',
 'soon',
 'south',
 'space',
 'special',
 'spend',
 'spirit',
 'stand',
 'star',
 'start',
 'state',
 'stay',
 'steal',
 'stop',
 'stori',
 'strang',
 'stranger',
 'street',
 'struggl',
 'student',
 'success',
 'suddenli',
 'summer',
 'surviv',
 'suspect',
 'taken',
 'tale',
 'talent',
 'target',
 'teacher',
 'team',
 'teen',
 'teenag',
 'tell',
 'terrifi',
 'terror',
 'test',
 'themselv',
 'thi',
 'thing',
 'think',
 'threaten',
 'thriller',
 'tim',
 'time',
 'togeth',
 'tom',
 'town',
 'track',
 'train',
 'transform',
 'trap',
 'travel',
 'tri',
 'trip',
 'troubl',
 'true',
 'truth',
 'turn',
 'tv',
 'ultim',
 'uncov',
 'unexpect',
 'unit',
 'unlik',
 'use',
 'vampir',
 'veri',
 'victim',
 'violent',
 'visit',
 'wa',
 'want',
 'war',
 'way',
 'wealthi',
 'west',
 'western',
 'white',
 'wife',
 'william',
 'win',
 'wit',
 'woman',
 'women',
 'work',
 'world',
 'writer',
 'wrong',
 'year',
 'years',
 'york',
 'young']

In [191]:
ps=PorterStemmer()

In [192]:
ps.stem('')

'love'

In [203]:
def stem(text):
    y=[]
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [201]:
string=movies['tags'][0]

In [204]:
print(stem(string))

in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron

In [205]:
movies['tags']=movies['tags'].apply(stem)

C:\WINDOWS\TEMP/ipykernel_11096/4136005365.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies['tags']=movies['tags'].apply(stem)

In [207]:
movies.head()['tags']

0    in the 22nd century, a parapleg marin is dispa...
1    captain barbossa, long believ to be dead, ha c...
2    a cryptic messag from bondâ€™ past send him on a...
3    follow the death of district attorney harvey d...
4    john carter is a war-weary, former militari ca...
Name: tags, dtype: object

In [209]:
cv.get_feature_names()

G:\Python\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 'accident',
 'accidentally',
 'action',
 'adventure',
 'affair',
 'age',
 'agent',
 'alien',
 'alive',
 'america',
 'american',
 'ancient',
 'angeles',
 'animation',
 'apart',
 'army',
 'arrives',
 'art',
 'artist',
 'attack',
 'attempt',
 'attempts',
 'away',
 'baby',
 'bad',
 'band',
 'based',
 'battle',
 'beautiful',
 'begin',
 'begins',
 'believe',
 'believes',
 'ben',
 'best',
 'big',
 'black',
 'blood',
 'body',
 'bond',
 'book',
 'born',
 'boss',
 'boy',
 'boyfriend',
 'break',
 'brien',
 'bring',
 'brings',
 'british',
 'brother',
 'brothers',
 'brown',
 'brucewillis',
 'business',
 'california',
 'called',
 'captain',
 'car',
 'career',
 'case',
 'caught',
 'century',
 'chance',
 'change',
 'changes',
 'characters',
 'charlie',
 'child',
 'childhood',
 'children',
 'christmas',
 'cia',
 'city',
 'class',
 'close',
 'club',
 'coach',
 'college',
 'come',
 'comedy',
 'comes',
 'coming',
 'community',
 'company',
 'connell',
 'connor',
 'control',
 'cop',
 'country',
 'couple',
 'crash',
 'crew',
 'crime',
 'criminal',
 'cross',
 'dangerous',
 'danny',
 'dark',
 'daughter',
 'david',
 'day',
 'days',
 'dead',
 'deadly',
 'deal',
 'death',
 'decide',
 'decides',
 'deep',
 'desperate',
 'despite',
 'destroy',
 'detective',
 'determined',
 'different',
 'director',
 'discover',
 'discovers',
 'doctor',
 'documentary',
 'does',
 'doesn',
 'dog',
 'don',
 'dr',
 'drama',
 'dream',
 'dreams',
 'drug',
 'early',
 'earth',
 'end',
 'ends',
 'enemy',
 'entire',
 'epic',
 'escape',
 'eve',
 'events',
 'eventually',
 'evil',
 'ex',
 'face',
 'faces',
 'fall',
 'falls',
 'family',
 'famous',
 'fantasy',
 'far',
 'fate',
 'father',
 'fbi',
 'fellow',
 'female',
 'fight',
 'film',
 'final',
 'finally',
 'finds',
 'following',
 'follows',
 'force',
 'forced',
 'forces',
 'foreign',
 'forever',
 'form',
 'frank',
 'free',
 'french',
 'friend',
 'friends',
 'friendship',
 'future',
 'game',
 'gang',
 'george',
 'gets',
 'getting',
 'girl',
 'girlfriend',
 'girls',
 'god',
 'goes',
 'going',
 'good',
 'government',
 'great',
 'group',
 'guy',
 'hands',
 'happens',
 'happy',
 'hard',
 'having',
 'head',
 'heart',
 'help',
 'hero',
 'high',
 'history',
 'hit',
 'hollywood',
 'home',
 'hope',
 'horror',
 'hotel',
 'house',
 'human',
 'hunt',
 'hunter',
 'husband',
 'identity',
 'ii',
 'including',
 'inside',
 'international',
 'involved',
 'island',
 'jack',
 'jackson',
 'james',
 'jean',
 'jimmy',
 'job',
 'john',
 'johnc',
 'johnson',
 'join',
 'joins',
 'jones',
 'journey',
 'jr',
 'just',
 'kid',
 'kidnapped',
 'kids',
 'kill',
 'killed',
 'killer',
 'killing',
 'king',
 'know',
 'known',
 'knows',
 'land',
 'late',
 'later',
 'law',
 'lawyer',
 'lead',
 'leader',
 'leading',
 'leads',
 'learn',
 'learns',
 'leave',
 'leaves',
 'led',
 'lee',
 'left',
 'legendary',
 'life',
 'like',
 'little',
 'live',
 'lives',
 'living',
 'local',
 'london',
 'long',
 'look',
 'looking',
 'lord',
 'los',
 'losing',
 'lost',
 'love',
 'major',
 'make',
 'makes',
 'making',
 'man',
 'marriage',
 'married',
 'martin',
 'mary',
 'master',
 'mattdamon',
 'meet',
 'meets',
 'men',
 'michael',
 'middle',
 'mike',
 'military',
 'mind',
 'missing',
 'mission',
 'mob',
 'modern',
 'mom',
 'money',
 'morganfreeman',
 'mother',
 'moves',
 'movie',
 'mr',
 'murder',
 'murdered',
 'music',
 'mysterious',
 'mystery',
 'named',
 'needs',
 'neill',
 'new',
 'nick',
 'night',
 'novel',
 'officer',
 'old',
 'order',
 'owner',
 'pair',
 'parents',
 'partner',
 'party',
 'past',
 'people',
 'perfect',
 'personal',
 'peter',
 'place',
 'plan',
 'planet',
 'plans',
 'play',
 'plot',
 'police',
 'political',
 'popular',
 'power',
 'powerful',
 'powers',
 'president',
 'prison',
 'professor',
 'protect',
 'puts',
 'queen',
 'quest',
 'quickly',
 'race',
 'real',
 'reality',
 'realizes',
 'really',
 'reilly',
 'relationship',
 'reporter',
 'rescue',
 'rest',
 'return',
 'returns',
 'revenge',
 'rich',
 'right',
 'road',
 'robert',
 'robertdeniro',
 'rock',
 'role',
 'romance',
 'romantic',
 'run',
 'ruthless',
 'sam',
 'samuell',
 'save',
 'school',
 'sciencefiction',
 'scott',
 'search',
 'second',
 'secret',
 'secrets',
 'security',
 'seemingly',
 'self',
 'sent',
 'series',
 'set',
 'sets',
 'sex',
 'ship',
 'singer',
 'single',
 'sister',
 'small',
 'smith',
 'society',
 'son',
 'soon',
 'south',
 'space',
 'special',
 'spirit',
 'star',
 'stars',
 'start',
 'starts',
 'state',
 'states',
 'stay',
 'stevebuscemi',
 'stop',
 'stories',
 'story',
 'strange',
 'street',
 'streets',
 'struggle',
 'struggles',
 'student',
 'students',
 'successful',
 'suddenly',
 'summer',
 'survive',
 'taken',
 'takes',
 'taking',
 'tale',
 'teacher',
 'team',
 'teen',
 'teenage',
 'teenager',
 'tells',
 'terrifying',
 'thing',
 'things',
 'thinks',
 'thomas',
 'thriller',
 'time',
 'tom',
 'town',
 'track',
 'train',
 'travel',
 'tries',
 'trip',
 'trouble',
 'true',
 'truth',
 'try',
 'trying',
 'turn',
 'turned',
 'turns',
 'tv',
 'uncle',
 'uncover',
 'unexpected',
 'united',
 'unlikely',
 'use',
 'using',
 'video',
 'village',
 'violent',
 'want',
 'wants',
 'war',
 'way',
 'wealthy',
 'wedding',
 'west',
 'western',
 'white',
 'wife',
 'wild',
 'win',
 'woman',
 'women',
 'work',
 'working',
 'works',
 'world',
 'writer',
 'wrong',
 'year',
 'years',
 'york',
 'young']

In [214]:
movies['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict samworthington zoesaldana sigourneyweav stephenlang michellerodriguez giovanniribisi joeldavidmoor cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyt scottlawr kellykilgour jamespatrickpitt seanpatrickmurphi peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblain-rozgay joncurri lukehawk woodyschultz petermensah soniaye jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibbi jodielandau julielamm cullenb.madden josephbradymadden frankietorr austinwilson sarawilson tamicawashington-mil lucybri nathanmeist gerryblair matthewchamberlain paulyat wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrel brandonjelk micahmoch hanniyahmuhammad christophernolen christaoliv aprilmariethoma bravitaa.threatt colinbleasdal mikebodnar mattclayton nicoledionn jamieharrison allanhenri anthonyingrub ashleyjefferi deanknowsley josephmika-hunt terrynotari kaipantano loganpithy stuartpollock raja garethruck rhiansheehan t.j.storm jodietaylor aliciavela-bailey richardwhitesid nikiezambo julenerene jamescameron'

In [215]:
movies.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [225]:
similarity=cosine_similarity(vectors)

In [226]:
similarity

array([[1.        , 0.2508726 , 0.15075567, ..., 0.        , 0.        ,
        0.        ],
       [0.2508726 , 1.        , 0.13867505, ..., 0.05439283, 0.        ,
        0.06201737],
       [0.15075567, 0.13867505, 1.        , ..., 0.04902903, 0.        ,
        0.        ],
       ...,
       [0.        , 0.05439283, 0.04902903, ..., 1.        , 0.08006408,
        0.0438529 ],
       [0.        , 0.        , 0.        , ..., 0.08006408, 1.        ,
        0.18257419],
       [0.        , 0.06201737, 0.        , ..., 0.0438529 , 0.18257419,
        1.        ]])

In [227]:
similarity[0].shape

(4806,)

In [237]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x: x[1])

[(0, 1.0),
 (2999, 0.533001790889026),
 (200, 0.45226701686664544),
 (61, 0.4351941398892446),
 (1194, 0.4351941398892446),
 (507, 0.42640143271122094),
 (577, 0.41812100500354543),
 (139, 0.40618119722996165),
 (2333, 0.40618119722996165),
 (208, 0.40451991747794525),
 (529, 0.40451991747794525),
 (72, 0.4029114820126901),
 (172, 0.40201512610368484),
 (973, 0.3892494720807615),
 (1444, 0.38138503569823695),
 (972, 0.37688918072220456),
 (1204, 0.37688918072220456),
 (151, 0.36927447293799825),
 (511, 0.36927447293799825),
 (4348, 0.36927447293799825),
 (91, 0.36563621206356534),
 (138, 0.36563621206356534),
 (467, 0.36563621206356534),
 (2075, 0.36563621206356534),
 (322, 0.36363636363636365),
 (1216, 0.3595732599803958),
 (495, 0.3481553119113957),
 (2786, 0.3481553119113957),
 (4405, 0.3481553119113957),
 (31, 0.3418817293789138),
 (33, 0.3418817293789138),
 (148, 0.3418817293789138),
 (2971, 0.33796318470968734),
 (2133, 0.3370999312316211),
 (3999, 0.3370999312316211),
 (122, 0.3344968040028363),
 (539, 0.3344968040028363),
 (2072, 0.3344968040028363),
 (4010, 0.3344968040028363),
 (27, 0.3302891295379082),
 (654, 0.3302891295379082),
 (187, 0.3289758474798845),
 (2372, 0.3289758474798845),
 (931, 0.3223291856101521),
 (937, 0.3223291856101521),
 (2148, 0.3223291856101521),
 (3428, 0.3223291856101521),
 (4048, 0.3223291856101521),
 (859, 0.3214121732666125),
 (3675, 0.3214121732666125),
 (68, 0.3198010745334156),
 (134, 0.3198010745334156),
 (256, 0.3198010745334156),
 (627, 0.3198010745334156),
 (1373, 0.3198010745334156),
 (2674, 0.3198010745334156),
 (3083, 0.3198010745334156),
 (262, 0.3143473067309657),
 (778, 0.3143473067309657),
 (232, 0.3113995776646092),
 (449, 0.3113995776646092),
 (483, 0.3113995776646092),
 (668, 0.3113995776646092),
 (1037, 0.3113995776646092),
 (2741, 0.3113995776646092),
 (14, 0.3077287274483319),
 (213, 0.3077287274483319),
 (127, 0.30463589792247125),
 (23, 0.30151134457776363),
 (98, 0.30151134457776363),
 (168, 0.30151134457776363),
 (199, 0.30151134457776363),
 (263, 0.30151134457776363),
 (330, 0.30151134457776363),
 (568, 0.30151134457776363),
 (813, 0.30151134457776363),
 (1530, 0.30151134457776363),
 (2035, 0.30151134457776363),
 (2645, 0.30151134457776363),
 (4083, 0.30151134457776363),
 (121, 0.29250896965085227),
 (166, 0.29250896965085227),
 (508, 0.29250896965085227),
 (1299, 0.29250896965085227),
 (1401, 0.29250896965085227),
 (1658, 0.29250896965085227),
 (2175, 0.29250896965085227),
 (2204, 0.29250896965085227),
 (870, 0.29012942659282975),
 (12, 0.2860387767736777),
 (35, 0.2860387767736777),
 (233, 0.2860387767736777),
 (466, 0.2860387767736777),
 (490, 0.2860387767736777),
 (715, 0.2860387767736777),
 (899, 0.2860387767736777),
 (1201, 0.2860387767736777),
 (2323, 0.2860387767736777),
 (2651, 0.2860387767736777),
 (3055, 0.2860387767736777),
 (4018, 0.2860387767736777),
 (4192, 0.2860387767736777),
 (102, 0.2849014411490949),
 (777, 0.2849014411490949),
 (46, 0.2842676218074806),
 (126, 0.2842676218074806),
 (167, 0.2842676218074806),
 (472, 0.2842676218074806),
 (581, 0.2842676218074806),
 (1004, 0.2842676218074806),
 (3340, 0.2842676218074806),
 (3, 0.2799462554779272),
 (420, 0.2799462554779272),
 (150, 0.27914526311954124),
 (5, 0.27668578554642986),
 (26, 0.27668578554642986),
 (111, 0.27668578554642986),
 (300, 0.27668578554642986),
 (678, 0.27668578554642986),
 (1113, 0.27668578554642986),
 (3255, 0.27668578554642986),
 (3622, 0.27668578554642986),
 (149, 0.27524094128159016),
 (1396, 0.27524094128159016),
 (56, 0.2727272727272727),
 (369, 0.2727272727272727),
 (1142, 0.2727272727272727),
 (1329, 0.2727272727272727),
 (1756, 0.2727272727272727),
 (2161, 0.2727272727272727),
 (3354, 0.2727272727272727),
 (3781, 0.2727272727272727),
 (3368, 0.2707651805369412),
 (4, 0.26967994498529685),
 (422, 0.26967994498529685),
 (1664, 0.26967994498529685),
 (2169, 0.26967994498529685),
 (2498, 0.26967994498529685),
 (2865, 0.26967994498529685),
 (3728, 0.26967994498529685),
 (3926, 0.26967994498529685),
 (1089, 0.26673253468463226),
 (425, 0.2631806779839076),
 (786, 0.2631806779839076),
 (1692, 0.2631806779839076),
 (2450, 0.2631806779839076),
 (3498, 0.2631806779839076),
 (3608, 0.2631806779839076),
 (28, 0.2611164839335468),
 (123, 0.2611164839335468),
 (260, 0.2611164839335468),
 (487, 0.2611164839335468),
 (505, 0.2611164839335468),
 (833, 0.2611164839335468),
 (935, 0.2611164839335468),
 (1274, 0.2611164839335468),
 (1524, 0.2611164839335468),
 (1945, 0.2611164839335468),
 (2378, 0.2611164839335468),
 (2916, 0.2611164839335468),
 (3621, 0.2611164839335468),
 (3721, 0.2611164839335468),
 (4673, 0.2611164839335468),
 (229, 0.2585438449975096),
 (230, 0.2585438449975096),
 (942, 0.2585438449975096),
 (1775, 0.2585438449975096),
 (342, 0.2584382953523688),
 (74, 0.25712973861328997),
 (412, 0.25712973861328997),
 (596, 0.25712973861328997),
 (746, 0.25712973861328997),
 (988, 0.25712973861328997),
 (1195, 0.25712973861328997),
 (1537, 0.25712973861328997),
 (3152, 0.25712973861328997),
 (7, 0.2514778453847726),
 (10, 0.2514778453847726),
 (41, 0.2514778453847726),
 (1920, 0.2514778453847726),
 (3407, 0.2514778453847726),
 (1, 0.2508726030021272),
 (175, 0.2508726030021272),
 (203, 0.2508726030021272),
 (219, 0.2508726030021272),
 (315, 0.2508726030021272),
 (329, 0.2508726030021272),
 (349, 0.2508726030021272),
 (794, 0.2508726030021272),
 (1071, 0.2508726030021272),
 (1077, 0.2508726030021272),
 (1086, 0.2508726030021272),
 (1109, 0.2508726030021272),
 (1158, 0.2508726030021272),
 (1488, 0.2508726030021272),
 (2760, 0.24784079854830485),
 (36, 0.2461829819586655),
 (84, 0.2461829819586655),
 (131, 0.2461829819586655),
 (584, 0.2461829819586655),
 (850, 0.2461829819586655),
 (1005, 0.2461829819586655),
 (1496, 0.2461829819586655),
 (1938, 0.2461829819586655),
 (1982, 0.2461829819586655),
 (94, 0.24174688920761409),
 (95, 0.24174688920761409),
 (207, 0.24174688920761409),
 (275, 0.24174688920761409),
 (413, 0.24174688920761409),
 (1009, 0.24174688920761409),
 (1015, 0.24174688920761409),
 (1275, 0.24174688920761409),
 (1383, 0.24174688920761409),
 (1942, 0.24174688920761409),
 (1996, 0.24174688920761409),
 (4403, 0.24174688920761409),
 (602, 0.24120907566221092),
 (618, 0.24120907566221092),
 (768, 0.24120907566221092),
 (2448, 0.24120907566221092),
 (2686, 0.24120907566221092),
 (160, 0.2383656473113981),
 (9, 0.23652495839563306),
 (158, 0.23652495839563306),
 (182, 0.23652495839563306),
 (217, 0.23652495839563306),
 (1237, 0.23652495839563306),
 (2820, 0.23652495839563306),
 (75, 0.23354968324845687),
 (87, 0.23354968324845687),
 (215, 0.23354968324845687),
 (305, 0.23354968324845687),
 (319, 0.23354968324845687),
 (332, 0.23354968324845687),
 (455, 0.23354968324845687),
 (461, 0.23354968324845687),
 (980, 0.23354968324845687),
 (1259, 0.23354968324845687),
 (1280, 0.23354968324845687),
 (1808, 0.23354968324845687),
 (1884, 0.23354968324845687),
 (2817, 0.23354968324845687),
 (2903, 0.23354968324845687),
 (4538, 0.23354968324845687),
 (170, 0.2321035412742638),
 (1233, 0.2321035412742638),
 (1297, 0.2321035412742638),
 (1878, 0.2321035412742638),
 (22, 0.2279211529192759),
 (165, 0.2279211529192759),
 (189, 0.2279211529192759),
 (373, 0.2279211529192759),
 (419, 0.2279211529192759),
 (1305, 0.2279211529192759),
 (1321, 0.2279211529192759),
 (1659, 0.2279211529192759),
 (2106, 0.2279211529192759),
 (2445, 0.2279211529192759),
 (3634, 0.2279211529192759),
 (4198, 0.2279211529192759),
 (4502, 0.2279211529192759),
 (16, 0.22613350843332272),
 (19, 0.22613350843332272),
 (76, 0.22613350843332272),
 (241, 0.22613350843332272),
 (242, 0.22613350843332272),
 (299, 0.22613350843332272),
 (894, 0.22613350843332272),
 (920, 0.22613350843332272),
 (1589, 0.22613350843332272),
 (1616, 0.22613350843332272),
 (1746, 0.22613350843332272),
 (2060, 0.22613350843332272),
 (234, 0.22395700438234173),
 (286, 0.22395700438234173),
 (572, 0.22395700438234173),
 (1455, 0.22395700438234173),
 (1831, 0.22395700438234173),
 (1479, 0.2201927530252721),
 (1906, 0.2201927530252721),
 (67, 0.2193817272381392),
 (70, 0.2193817272381392),
 (271, 0.2193817272381392),
 (292, 0.2193817272381392),
 (334, 0.2193817272381392),
 (745, 0.2193817272381392),
 (781, 0.2193817272381392),
 (854, 0.2193817272381392),
 (1056, 0.2193817272381392),
 (1080, 0.2193817272381392),
 (1688, 0.2193817272381392),
 (1833, 0.2193817272381392),
 (2053, 0.2193817272381392),
 (2181, 0.2193817272381392),
 (2396, 0.2193817272381392),
 (2683, 0.2193817272381392),
 (2831, 0.2193817272381392),
 (3805, 0.2193817272381392),
 (3982, 0.2193817272381392),
 (307, 0.21759706994462233),
 (11, 0.21661214442955296),
 (45, 0.21661214442955296),
 (153, 0.21661214442955296),
 (228, 0.21661214442955296),
 (3212, 0.21469688008935398),
 (164, 0.21320071635561047),
 (243, 0.21320071635561044),
 (278, 0.21320071635561044),
 (302, 0.21320071635561044),
 (341, 0.21320071635561044),
 (371, 0.21320071635561044),
 (732, 0.21320071635561044),
 (960, 0.21320071635561044),
 (1096, 0.21320071635561044),
 (1523, 0.21320071635561044),
 (2652, 0.21320071635561044),
 (2661, 0.21320071635561044),
 (3355, 0.21320071635561044),
 (3389, 0.21320071635561044),
 (4336, 0.21320071635561044),
 (159, 0.21320071635561041),
 (216, 0.21320071635561041),
 (547, 0.21320071635561041),
 (808, 0.21320071635561041),
 (840, 0.21320071635561041),
 (1139, 0.21320071635561041),
 (1147, 0.21320071635561041),
 (1276, 0.21320071635561041),
 (1501, 0.21320071635561041),
 (1727, 0.21320071635561041),
 (1850, 0.21320071635561041),
 (2259, 0.21320071635561041),
 (2331, 0.21320071635561041),
 (2521, 0.21320071635561041),
 (3155, 0.21320071635561041),
 (3527, 0.21320071635561041),
 (4011, 0.21320071635561041),
 (143, 0.20994555243259122),
 (238, 0.20994555243259122),
 (2650, 0.20994555243259122),
 (400, 0.2075143391598224),
 (428, 0.2075143391598224),
 (476, 0.2075143391598224),
 (582, 0.2075143391598224),
 (587, 0.2075143391598224),
 (784, 0.2075143391598224),
 (814, 0.2075143391598224),
 (1030, 0.2075143391598224),
 (1306, 0.2075143391598224),
 (2596, 0.2075143391598224),
 (3755, 0.2075143391598224),
 (4019, 0.2075143391598224),
 (4657, 0.2075143391598224),
 (403, 0.20683507599800766),
 (1534, 0.20683507599800766),
 (1741, 0.20683507599800766),
 (1783, 0.20683507599800766),
 (589, 0.2038588765750502),
 (39, 0.20225995873897262),
 (43, 0.20225995873897262),
 (50, 0.20225995873897262),
 (96, 0.20225995873897262),
 (97, 0.20225995873897262),
 (101, 0.20225995873897262),
 (152, 0.20225995873897262),
 (174, 0.20225995873897262),
 (312, 0.20225995873897262),
 (402, 0.20225995873897262),
 (478, 0.20225995873897262),
 (632, 0.20225995873897262),
 (773, 0.20225995873897262),
 (1047, 0.20225995873897262),
 (1082, 0.20225995873897262),
 (1344, 0.20225995873897262),
 (2109, 0.20225995873897262),
 (2163, 0.20225995873897262),
 (2556, 0.20225995873897262),
 (3620, 0.20225995873897262),
 (17, 0.20100756305184242),
 (105, 0.20100756305184242),
 (205, 0.20100756305184242),
 (249, 0.20100756305184242),
 (276, 0.20100756305184242),
 (331, 0.20100756305184242),
 (336, 0.20100756305184242),
 (358, 0.20100756305184242),
 (381, 0.20100756305184242),
 (537, 0.20100756305184242),
 (624, 0.20100756305184242),
 (695, 0.20100756305184242),
 (744, 0.20100756305184242),
 (866, 0.20100756305184242),
 (989, 0.20100756305184242),
 (995, 0.20100756305184242),
 (1282, 0.20100756305184242),
 (1335, 0.20100756305184242),
 (1410, 0.20100756305184242),
 (2091, 0.20100756305184242),
 (2190, 0.20100756305184242),
 (2355, 0.20100756305184242),
 (2395, 0.20100756305184242),
 (2480, 0.20100756305184242),
 (2515, 0.20100756305184242),
 (2854, 0.20100756305184242),
 (3356, 0.20100756305184242),
 (3374, 0.20100756305184242),
 (3572, 0.20100756305184242),
 (3730, 0.20100756305184242),
 (4099, 0.20100756305184242),
 (4165, 0.20100756305184242),
 (4279, 0.20100756305184242),
 (4568, 0.20100756305184242),
 (1965, 0.19827263883864388),
 (30, 0.19738550848793068),
 (52, 0.19738550848793068),
 (71, 0.19738550848793068),
 (294, 0.19738550848793068),
 (473, 0.19738550848793068),
 (728, 0.19738550848793068),
 (932, 0.19738550848793068),
 (1269, 0.19738550848793068),
 (1290, 0.19738550848793068),
 (2253, 0.19738550848793068),
 (2409, 0.19738550848793068),
 (2256, 0.1956463952178074),
 (3611, 0.1956463952178074),
 (83, 0.19312181983410703),
 (595, 0.1928473039599675),
 (600, 0.1928473039599675),
 (655, 0.19284730395996746),
 (735, 0.19284730395996746),
 (788, 0.19284730395996746),
 (922, 0.19284730395996746),
 (1519, 0.19284730395996746),
 (1623, 0.19284730395996746),
 (1701, 0.19284730395996746),
 (2496, 0.19284730395996746),
 (3322, 0.19284730395996746),
 (4626, 0.19284730395996746),
 (62, 0.19069251784911848),
 (104, 0.19069251784911848),
 (109, 0.19069251784911848),
 (157, 0.19069251784911848),
 (513, 0.19069251784911848),
 (1137, 0.19069251784911848),
 (1141, 0.19069251784911848),
 (1156, 0.19069251784911848),
 (1408, 0.19069251784911848),
 (1621, 0.19069251784911848),
 (1673, 0.19069251784911848),
 (1703, 0.19069251784911848),
 (1707, 0.19069251784911848),
 (2381, 0.19069251784911848),
 (2593, 0.19069251784911848),
 (2772, 0.19069251784911848),
 (2890, 0.19069251784911848),
 (2970, 0.19069251784911848),
 (3151, 0.19069251784911848),
 (3832, 0.19069251784911848),
 (4112, 0.19069251784911848),
 (4331, 0.19069251784911848),
 (4472, 0.19069251784911848),
 (4566, 0.19069251784911848),
 (4623, 0.19069251784911848),
 (40, 0.18860838403857944),
 (184, 0.18860838403857944),
 (270, 0.18860838403857944),
 (540, 0.18860838403857944),
 (1278, 0.18860838403857944),
 (1497, 0.18860838403857944),
 (1639, 0.18860838403857944),
 (1749, 0.18860838403857944),
 (3874, 0.18860838403857944),
 (3881, 0.18860838403857944),
 (4268, 0.18860838403857944),
 (15, 0.18463723646899913),
 (480, 0.18463723646899913),
 (979, 0.18463723646899913),
 (1099, 0.18463723646899913),
 (1161, 0.18463723646899913),
 (1614, 0.18463723646899913),
 (1632, 0.18463723646899913),
 (2128, 0.18463723646899913),
 (2400, 0.18463723646899913),
 (2439, 0.18463723646899913),
 (3905, 0.18463723646899913),
 (1322, 0.18392019594868114),
 (90, 0.18181818181818182),
 (142, 0.18181818181818182),
 (181, 0.18181818181818182),
 (204, 0.18181818181818182),
 (209, 0.18181818181818182),
 (237, 0.18181818181818182),
 (245, 0.18181818181818182),
 (259, 0.18181818181818182),
 (389, 0.18181818181818182),
 (594, 0.18181818181818182),
 (1076, 0.18181818181818182),
 (1092, 0.18181818181818182),
 (1240, 0.18181818181818182),
 (1241, 0.18181818181818182),
 (1254, 0.18181818181818182),
 (1292, 0.18181818181818182),
 (1323, 0.18181818181818182),
 (1334, 0.18181818181818182),
 (1364, 0.18181818181818182),
 (1365, 0.18181818181818182),
 (1474, 0.18181818181818182),
 (1575, 0.18181818181818182),
 (1713, 0.18181818181818182),
 (2326, 0.18181818181818182),
 (2584, 0.18181818181818182),
 (2680, 0.18181818181818182),
 (2731, 0.18181818181818182),
 (2856, 0.18181818181818182),
 (3549, 0.18181818181818182),
 (3663, 0.18181818181818182),
 (3891, 0.18181818181818182),
 (3949, 0.18181818181818182),
 (3978, 0.18181818181818182),
 (4079, 0.18181818181818182),
 (4087, 0.18181818181818182),
 (55, 0.18090680674665818),
 (108, 0.18090680674665818),
 (447, 0.18090680674665818),
 (543, 0.18090680674665818),
 (836, 0.18090680674665818),
 (1367, 0.18090680674665818),
 (1847, 0.18090680674665818),
 (2243, 0.18090680674665818),
 (3553, 0.18090680674665818),
 (59, 0.1797866299901979),
 (4429, 0.1797866299901979),
 (38, 0.17782168978975482),
 (51, 0.1773937187967248),
 (183, 0.1773937187967248),
 (235, 0.1773937187967248),
 (383, 0.1773937187967248),
 (586, 0.1773937187967248),
 (1293, 0.1773937187967248),
 (2404, 0.1773937187967248),
 (2592, 0.1773937187967248),
 (3162, 0.1773937187967248),
 (3309, 0.1773937187967248),
 (4483, 0.1773937187967248),
 (1491, 0.17644616831014637),
 (37, 0.17407765595569785),
 (82, 0.17407765595569785),
 (106, 0.17407765595569785),
 (117, 0.17407765595569785),
 (206, 0.17407765595569785),
 (212, 0.17407765595569785),
 (257, 0.17407765595569785),
 (267, 0.17407765595569785),
 (309, 0.17407765595569785),
 (356, 0.17407765595569785),
 (485, 0.17407765595569785),
 (634, 0.17407765595569785),
 (660, 0.17407765595569785),
 (984, 0.17407765595569785),
 (1073, 0.17407765595569785),
 (1087, 0.17407765595569785),
 (1145, 0.17407765595569785),
 (1289, 0.17407765595569785),
 (1347, 0.17407765595569785),
 (1457, 0.17407765595569785),
 (1631, 0.17407765595569785),
 (1771, 0.17407765595569785),
 (2052, 0.17407765595569785),
 (2218, 0.17407765595569785),
 (2270, 0.17407765595569785),
 (2622, 0.17407765595569785),
 (3072, 0.17407765595569785),
 (3093, 0.17407765595569785),
 (3103, 0.17407765595569785),
 (3225, 0.17407765595569785),
 (3285, 0.17407765595569785),
 (3588, 0.17407765595569785),
 (3720, 0.17407765595569785),
 (3838, 0.17407765595569785),
 (3879, 0.17407765595569785),
 (3901, 0.17407765595569785),
 (3907, 0.17407765595569785),
 (4045, 0.17407765595569785),
 (4061, 0.17407765595569785),
 (4123, 0.17407765595569785),
 (4636, 0.17407765595569785),
 (4641, 0.17407765595569785),
 (4691, 0.17407765595569785),
 (4790, 0.17407765595569785),
 (29, 0.1709408646894569),
 (93, 0.1709408646894569),
 (107, 0.1709408646894569),
 (169, 0.1709408646894569),
 (410, 0.1709408646894569),
 (661, 0.1709408646894569),
 (734, 0.1709408646894569),
 (1273, 0.1709408646894569),
 (1459, 0.1709408646894569),
 (1617, 0.1709408646894569),
 (3935, 0.1709408646894569),
 (103, 0.16796775328675628),
 (1220, 0.16796775328675628),
 (1462, 0.16796775328675628),
 (3617, 0.16796775328675628),
 (4711, 0.16796775328675628),
 (78, 0.16724840200141816),
 (144, 0.16724840200141816),
 (244, 0.16724840200141816),
 (290, 0.16724840200141816),
 (362, 0.16724840200141816),
 (603, 0.16724840200141816),
 (626, 0.16724840200141816),
 (645, 0.16724840200141816),
 (691, 0.16724840200141816),
 (718, 0.16724840200141816),
 (790, 0.16724840200141816),
 (800, 0.16724840200141816),
 (834, 0.16724840200141816),
 (863, 0.16724840200141816),
 (898, 0.16724840200141816),
 (1032, 0.16724840200141816),
 (1079, 0.16724840200141816),
 (1121, 0.16724840200141816),
 (1242, 0.16724840200141816),
 (1362, 0.16724840200141816),
 (1363, 0.16724840200141816),
 (1434, 0.16724840200141816),
 (1438, 0.16724840200141816),
 (1513, 0.16724840200141816),
 (1686, 0.16724840200141816),
 (1796, 0.16724840200141816),
 (2090, 0.16724840200141816),
 (2241, 0.16724840200141816),
 (2274, 0.16724840200141816),
 (2354, 0.16724840200141816),
 (2562, 0.16724840200141816),
 (2709, 0.16724840200141816),
 (3022, 0.16724840200141816),
 (3253, 0.16724840200141816),
 (3452, 0.16724840200141816),
 (4196, 0.16724840200141816),
 (4355, 0.16724840200141816),
 (4672, 0.16724840200141816),
 (4737, 0.16724840200141816),
 (58, 0.1651445647689541),
 (799, 0.1651445647689541),
 (997, 0.1651445647689541),
 (1175, 0.1651445647689541),
 (1191, 0.1651445647689541),
 (4392, 0.1651445647689541),
 (129, 0.1624591083221647),
 (301, 0.1624591083221647),
 (782, 0.1624591083221647),
 (1574, 0.1624591083221647),
 (88, 0.16116459280507606),
 (210, 0.16116459280507606),
 (227, 0.16116459280507606),
 (340, 0.16116459280507606),
 (405, 0.16116459280507606),
 (411, 0.16116459280507606),
 (597, 0.16116459280507606),
 (604, 0.16116459280507606),
 (762, 0.16116459280507606),
 (805, 0.16116459280507606),
 (987, 0.16116459280507606),
 (1085, 0.16116459280507606),
 (1327, 0.16116459280507606),
 (1492, 0.16116459280507606),
 (1560, 0.16116459280507606),
 (1726, 0.16116459280507606),
 (1827, 0.16116459280507606),
 (1997, 0.16116459280507606),
 (2216, 0.16116459280507606),
 (2297, 0.16116459280507606),
 (2309, 0.16116459280507606),
 (2762, 0.16116459280507606),
 (2957, 0.16116459280507606),
 (3133, 0.16116459280507606),
 (3396, 0.16116459280507606),
 (3678, 0.16116459280507606),
 (3770, 0.16116459280507606),
 (3890, 0.16116459280507606),
 (4316, 0.16116459280507606),
 (79, 0.1599005372667078),
 (939, 0.15974461276617435),
 (363, 0.1574591643244434),